a_tensor_initialization

In [11]:
import torch

# torch.Tensor class
t1 = torch.Tensor([1, 2, 3], device='cpu') #tensor는 기본적으로 float32로 생성된다.
print(t1.dtype)   # >>> torch.float32 / t1의 데이터 타입을 알 수 있다.
print(t1.device)  # >>> cpu / t1이 할당된 디바이스를 알 수 있다.
print(t1.requires_grad)  # >>> False / 기울기 추적을 하는지 안 하는지 알 수 있다.
print(t1.size())  # torch.Size([3]) / t1의 크기를 알 수 잇다.
print(t1.shape)   # torch.Size([3]) / t1의 크기를 알 수 있다.

# if you have gpu device
# t1_cuda = t1.to(torch.device('cuda'))
# or you can use shorthand
# t1_cuda = t1.cuda()
t1_cpu = t1.cpu()

print("#" * 50, 1)

# torch.tensor function
t2 = torch.tensor([1, 2, 3], device='cpu') # int64 타입의 텐서를 CPU에 생성한다.
print(t2.dtype)  # >>> torch.int64 / 정수 리스트는 int64로 생성된다.
print(t2.device)  # >>> cpu
print(t2.requires_grad)  # >>> False
print(t2.size())  # torch.Size([3])
print(t2.shape)  # torch.Size([3])

# if you have gpu device
# t2_cuda = t2.to(torch.device('cuda'))
# or you can use shorthand
# t2_cuda = t2.cuda()
t2_cpu = t2.cpu()

print("#" * 50, 2)

a1 = torch.tensor(1)			     # shape: torch.Size([]), ndims(=rank): 0
print(a1.shape, a1.ndim) # 텐서의 shape과 차원을 출력한다.

a2 = torch.tensor([1])		  	     # shape: torch.Size([1]), ndims(=rank): 1
print(a2.shape, a2.ndim)

a3 = torch.tensor([1, 2, 3, 4, 5])   # shape: torch.Size([5]), ndims(=rank): 1
print(a3.shape, a3.ndim)

a4 = torch.tensor([[1], [2], [3], [4], [5]])   # shape: torch.Size([5, 1]), ndims(=rank): 2
print(a4.shape, a4.ndim)

a5 = torch.tensor([                 # shape: torch.Size([3, 2]), ndims(=rank): 2
    [1, 2],
    [3, 4],
    [5, 6]
])
print(a5.shape, a5.ndim)

a6 = torch.tensor([                 # shape: torch.Size([3, 2, 1]), ndims(=rank): 3
    [[1], [2]],
    [[3], [4]],
    [[5], [6]]
])
print(a6.shape, a6.ndim)

a7 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 1]), ndims(=rank): 4
    [[[1], [2]]],
    [[[3], [4]]],
    [[[5], [6]]]
])
print(a7.shape, a7.ndim)

a8 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 3]), ndims(=rank): 4
    [[[1, 2, 3], [2, 3, 4]]],
    [[[3, 1, 1], [4, 4, 5]]],
    [[[5, 6, 2], [6, 3, 1]]]
])
print(a8.shape, a8.ndim)


a9 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 3, 1]), ndims(=rank): 5
    [[[[1], [2], [3]], [[2], [3], [4]]]],
    [[[[3], [1], [1]], [[4], [4], [5]]]],
    [[[[5], [6], [2]], [[6], [3], [1]]]]
])
print(a9.shape, a9.ndim)

a10 = torch.tensor([                 # shape: torch.Size([4, 5]), ndims(=rank): 2
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
])
print(a10.shape, a10.ndim)

a10 = torch.tensor([                 # shape: torch.Size([4, 1, 5]), ndims(=rank): 3
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
])
print(a10.shape, a10.ndim)

a11 = torch.tensor([                 # ValueError: expected sequence of length 3 at dim 3 (got 2)
    [[[1, 2, 3], [4, 5]]],           # 차원이 일관되지 않아 발생한 에러다.
    [[[1, 2, 3], [4, 5]]],           # 동일한 차원에 속하는 요소들의 길이가 일치해야 텐서를 구성할 수 있다.
    [[[1, 2, 3], [4, 5]]],           # 따라서 [4,5]의 길이를 3으로 맞추거나, 다른 요소의 길이를 줄여야 한다.
    [[[1, 2, 3], [4, 5]]],
])



torch.float32
cpu
False
torch.Size([3])
torch.Size([3])
################################################## 1
torch.int64
cpu
False
torch.Size([3])
torch.Size([3])
################################################## 2
torch.Size([]) 0
torch.Size([1]) 1
torch.Size([5]) 1
torch.Size([5, 1]) 2
torch.Size([3, 2]) 2
torch.Size([3, 2, 1]) 3
torch.Size([3, 1, 2, 1]) 4
torch.Size([3, 1, 2, 3]) 4
torch.Size([3, 1, 2, 3, 1]) 5
torch.Size([4, 5]) 2
torch.Size([4, 1, 5]) 3


ValueError: expected sequence of length 3 at dim 3 (got 2)

* torch.Tensor와 torch.tensor의 차이
    * torch.Tensor은 float32로 데이터 타입이 고정되어 있고, torch.tensor는 전달된 값의 타입에 따라 자동으로 자료형이 결정된다.
* torch.size()와 torch.shape의 차이
    * torch.size()는 함수처럼 호출하는 방식이고, torch.shape은 속성으로 바로 접근하는 방식이다. 
    * 하지만, 결국 둘은 동일한 정보를 반환한다.

b_tensor_initialization_copy

In [12]:
import torch
import numpy as np

# 리스트 l1을 사용해 torch.Tensor로 텐서를 생성한다.
l1 = [1, 2, 3]
t1 = torch.Tensor(l1) # l1의 값을 복사하여 새로운 텐서를 만든다.

# 리스트 l2를 사용해 torch.tensor로 텐서를 생성한다.
l2 = [1, 2, 3]
t2 = torch.tensor(l2)

# 리스트 l3를 사용해 torch.as_tensor로 텐서를 생성한다.
l3 = [1, 2, 3]
t3 = torch.as_tensor(l3) # 리스트가 복사되는 것임으로 l3의 변경이 t3에게 영향을 미치지 않는다.

# 리스트 값을 변경한다.
l1[0] = 100
l2[0] = 100
l3[0] = 100

# 각 텐서를 출력한다. 각 값은 변하지 않는다.
print(t1)
print(t2)
print(t3)

print("#" * 100)

# NumPy 배열 l4를 사용해 torch.Tensor로 텐서를 생성한다.
l4 = np.array([1, 2, 3])
t4 = torch.Tensor(l4)  # NumPy 배열을 복사하여 새로운 텐서를 만든다.

# NumPy 배열 l5를 사용해 torch.tensor로 텐서를 생성한다.
l5 = np.array([1, 2, 3])
t5 = torch.tensor(l5)  # NumPy 배열을 복사하여 새로운 텐서를 만든다.

# NumPy 배열 l6를 사용해 torch.as_tensor로 텐서를 생성한다.
l6 = np.array([1, 2, 3])
t6 = torch.as_tensor(l6)  # NumPy 배열과 메모리를 공유하고, l6의 변경이 t6에 영향을 준다.

# NumPy 배열 값을 변경한다.
l4[0] = 100
l5[0] = 100
l6[0] = 100

# 각 텐서를 출력한다.
print(t4)
print(t5)
print(t6) # t4와 t5와 달리 torch.as_tensor로 생성된 텐서는 l6와 메모리를 공유하기 때문에 값이 변경된다.


tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])
####################################################################################################
tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([100,   2,   3])


c_tensor_initialization_constant_values

In [13]:
import torch

# 크기 (5,)인 1로 채워진 텐서를 생성한다.
t1 = torch.ones(size=(5,))  # or torch.ones(5)
# t1과 같은 크기와 자료형을 가지는 1로 채워진 텐서를 생성한다.
t1_like = torch.ones_like(input=t1)
print(t1)  # >>> tensor([1., 1., 1., 1., 1.])
print(t1_like)  # >>> tensor([1., 1., 1., 1., 1.])

# 크기 (6,)인 0으로 채워진 텐서를 생성한다.
t2 = torch.zeros(size=(6,))  # or torch.zeros(6)
# t2와 같은 크기와 자료형을 가지는 0으로 채워진 텐서를 생성한다.
t2_like = torch.zeros_like(input=t2)
print(t2)  # >>> tensor([0., 0., 0., 0., 0., 0.])
print(t2_like)  # >>> tensor([0., 0., 0., 0., 0., 0.])

# 크기 (4,)인 텐서를 생성한다.
t3 = torch.empty(size=(4,))  # or torch.zeros(4)
# t3와 같은 크기와 자료형을 가지는 텐서를 생성한다.
t3_like = torch.empty_like(input=t3)
# 초기화 되지 않은 값이 텐서에 들어갈 수 있다.
print(t3)  # >>> tensor([0., 0., 0., 0.])
print(t3_like)  # >>> tensor([0., 0., 0., 0.])

# 3x3 크기의 단위 행렬을 생성한다.
t4 = torch.eye(n=3)
print(t4)

tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.])
tensor([0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0.])
tensor([1.0000, 1.3828, 0.0000, 0.0000])
tensor([1., nan, 3., 0.])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


d_tensor_initialization_random_values

In [14]:
import torch

# 지정된 범위에서 임의의 정수로 텐서 생성
t1 = torch.randint(low=10, high=20, size=(1, 2))
print(t1)

# (1,3) 크기의 텐서를 생성하고, 0과 1사이의 균등 분포에서 값을 샘플링한다.
t2 = torch.rand(size=(1, 3))
print(t2)

# (1,3) 크기의 텐서를 생성하고, 표준 정규 분포(N(0,1))에서 값을 샘플링한다.
t3 = torch.randn(size=(1, 3))
print(t3)

# (3,2) 크기의 텐서를 생성하고, 평균이 10.0, 표준편차가 1.0인 정규 분포에서 샘플링한다.
t4 = torch.normal(mean=10.0, std=1.0, size=(3, 2))
print(t4)

# 0.0에서 5.0까지 3개의 값을 균등하게 나눈 텐서를 생성한다.
t5 = torch.linspace(start=0.0, end=5.0, steps=3)
print(t5)

# 0부터 4까지의 정수로 이루어진 텐서를 생성한다.
t6 = torch.arange(5)
print(t6)

print("#" * 30)

# 시드를 설정하여 랜덤 숫자를 만들어낸다.
torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

print()

# 시드를 재설정하여 랜덤 숫자를 만들어낸다.
torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)


tensor([[17, 12]])
tensor([[0.0453, 0.5035, 0.9978]])
tensor([[0.7419, 0.5923, 0.2908]])
tensor([[ 9.2270, 10.0961],
        [ 9.4067,  9.5878],
        [10.0763, 11.1161]])
tensor([0.0000, 2.5000, 5.0000])
tensor([0, 1, 2, 3, 4])
##############################
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


* torch.manual_seed()는 랜덤 시드를 고정하여 랜덤 숫자가 동일할 수 있도록 만들어준다.

e_tensor_type_conversion

In [16]:
import torch

a = torch.ones((2, 3))
print(a.dtype)

b = torch.ones((2, 3), dtype=torch.int16)
print(b)

# (2,3) 크기의 텐서를 생성하고, 0고 1 사이의 균등 분포에서 값을 샘플링한 후 20을 곱한다.
c = torch.rand((2, 3), dtype=torch.float64) * 20.
print(c)

# 텐서 b의 데이터 타입을 int32로 변환한다.
d = b.to(torch.int32)
print(d)

# (10, 2) 크기의 1로 채워진 텐서를 생성하고, 데이터 타입을 float64로 설정한다.
double_d = torch.ones(10, 2, dtype=torch.double)
# (1, 2) 크기의 텐서를 생성하고, 데이터 타입을 int16으로 설정한다.
short_e = torch.tensor([[1, 2]], dtype=torch.short)

# (10,2) 크기의 0으로 채워진 텐서를 생성하고 데이터 타입을 float64로 설정한다.
double_d = torch.zeros(10, 2).double()
# (10, 2) 크기의 1로 채워진 텐서를 생성하고, 데이터 타입을 int16으로 설정한다.
short_e = torch.ones(10, 2).short()

# (10,2) 크기의 0으로 채워진 텐서를 생성하고, 데이터 타입을 float64로 설정한다.
double_d = torch.zeros(10, 2).to(torch.double)
# (10, 2) 크기의 1로 채워진 텐서를 생성하고, 데이터 타입을 int16으로 설정한다.
short_e = torch.ones(10, 2).to(dtype=torch.short)

# (10, 2) 크기의 0으로 채워진 텐서를 생성하고, 데이터 타입을 float64로 설정한다.
double_d = torch.zeros(10, 2).type(torch.double)
# (10, 2) 크기의 1로 채워진 텐서를 생성하고, 데이터 타입을 int16으로 설정한다.
short_e = torch.ones(10, 2). type(dtype=torch.short)

print(double_d.dtype)
print(short_e.dtype)

# (5, ) 크기의 표준 정규 분표에서 샘플링한 값을 가지는 텐서를 생성하고 데이터 타입을 float64로 설정한다.
double_f = torch.rand(5, dtype=torch.double)
# 텐서 double_f를 inst16으로 변환한다.
short_g = double_f.to(torch.short)
# double_f와 short_g의 곱의 데이터 타입을 출력한다.
print((double_f * short_g).dtype)


torch.float32
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[11.6692, 18.3283,  0.2118],
        [18.4972,  9.8370,  3.8937]], dtype=torch.float64)
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
torch.float64
torch.int16
torch.float64


f_tensor_type_conversion

In [17]:
import torch

# (2, 3) 크기의 1로 채워진 텐서를 생성한다.
t1 = torch.ones(size=(2, 3))
t2 = torch.ones(size=(2, 3))
# 두 텐서를 더한다.
t3 = torch.add(t1, t2)
t4 = t1 + t2
print(t3)
print(t4)

print("#" * 30)

# 두 텐서를 뺀다.
t5 = torch.sub(t1, t2)
t6 = t1 - t2
print(t5)
print(t6)

print("#" * 30)

# 두 텐서를 곱한다.
t7 = torch.mul(t1, t2)
t8 = t1 * t2
print(t7)
print(t8)

print("#" * 30)

# 두 텐서를 나눈다.
t9 = torch.div(t1, t2)
t10 = t1 / t2
print(t9)
print(t10)

tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
##############################
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
##############################
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
##############################
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


* torch.add() (sub, mul, div)는 연산자로 대체할 수 있다.

g_tensor_operations_mm

In [18]:
import torch

# [2,3]인 1차원 텐서와 [2,1]인 1차원 텐서를 내적 계산한다.
t1 = torch.dot(
  torch.tensor([2, 3]), torch.tensor([2, 1])
)
print(t1, t1.size())

# 정규 분포에서 무작위로 추출한 난수를 생성하여 (2, 3) 크기인 텐서를 반환한다.
t2 = torch.randn(2, 3)
# 정규 분포에서 무작위로 추출한 난수를 생성하여 (3, 2) 크기인 텐서를 반환한다.
t3 = torch.randn(3, 2)
# t2와 t3를 내적 계산한다.
t4 = torch.mm(t2, t3)
print(t4, t4.size())

# 정규 분포에서 무작위로 추출한 난수를 생성하여 (10, 3, 4) 크기인 텐서를 반환한다.
t5 = torch.randn(10, 3, 4)
# 정규 분포에서 무작위로 추출한 난수를 생성하여 (10, 4, 5) 크기인 텐서를 반환한다.
t6 = torch.randn(10, 4, 5)
# t5와 t6를 내적 계산한다.
t7 = torch.bmm(t5, t6)
print(t7.size())

tensor(7) torch.Size([])
tensor([[-4.9983, -1.9715],
        [-2.0698,  0.6196]]) torch.Size([2, 2])
torch.Size([10, 3, 5])


h_tensor_operations_matmul

In [19]:
import torch

# vector x vector: dot product
# 크기가 3인 1차원 텐서 2개를 생성한다.
t1 = torch.randn(3)
t2 = torch.randn(3)
# 텐서를 내적한 후 텐서의 사이즈를 출력한다.
print(torch.matmul(t1, t2).size())  # torch.Size([])

# matrix x vector: broadcasted dot
t3 = torch.randn(3, 4) # 크기 [3,4]의 2차원 텐서를 생성한다.
t4 = torch.randn(4) # 크기가 4인 1차원 텐서를 생성한다.
print(torch.matmul(t3, t4).size())  # torch.Size([3])

# batched matrix x vector: broadcasted dot
t5 = torch.randn(10, 3, 4) # 크기 [10, 3, 4]의 3차원 텐서를 생성한다.
t6 = torch.randn(4) # 크기 4의 1차원 텐서를 생성한다.
print(torch.matmul(t5, t6).size())  # torch.Size([10, 3])

# batched matrix x batched matrix: bmm
t7 = torch.randn(10, 3, 4) # 크기 [10, 3, 4]의 3차원 텐서를 생성한다.
t8 = torch.randn(10, 4, 5) # 크기 [10, 4, 5]의 3차원 텐서를 생성한다.
print(torch.matmul(t7, t8).size())  # torch.Size([10, 3, 5])

# batched matrix x matrix: bmm
t9 = torch.randn(10, 3, 4) # 크기 [10, 3, 4]의 3차원 텐서를 생성한다.
t10 = torch.randn(4, 5) # 크기 [4, 5]의 2차원 텐서를 생성한다.
print(torch.matmul(t9, t10).size())  # torch.Size([10, 3, 5])

torch.Size([])
torch.Size([3])
torch.Size([10, 3])
torch.Size([10, 3, 5])
torch.Size([10, 3, 5])


* torch.matmul()은 torch.mm()과 달리 broadcasting이 가능하다.

i_tensor_broadcasting

In [20]:
import torch

# t1과 t2를 곱한다. (broadcasting)
t1 = torch.tensor([1.0, 2.0, 3.0])
t2 = 2.0
print(t1 * t2)

print("#" * 50, 1)

# t3에서 t4를 뺀다.
t3 = torch.tensor([[0, 1], [2, 4], [10, 10]])
t4 = torch.tensor([4, 5])
print(t3 - t4) # t4가 각 행에 브로드캐스트된다.

print("#" * 50, 2)

# t5에 대하여 사칙연산을 한다.
t5 = torch.tensor([[1., 2.], [3., 4.]])
print(t5 + 2.0)  # t5.add(2.0)
print(t5 - 2.0)  # t5.sub(2.0)
print(t5 * 2.0)  # t5.mul(2.0)
print(t5 / 2.0)  # t5.div(2.0)

print("#" * 50, 3)

# 각 원소를 255로 나눠 정규화한다.
def normalize(x):
  return x / 255

# 3개의 채널을 가진 28x28의 텐서를 생성한다.
t6 = torch.randn(3, 28, 28)
# t6을 정규화한 후의 크기를 출력한다.
print(normalize(t6).size())

print("#" * 50, 4)

t7 = torch.tensor([[1, 2], [0, 3]])  # torch.Size([2, 2])
t8 = torch.tensor([[3, 1]])  # torch.Size([1, 2])
t9 = torch.tensor([[5], [2]])  # torch.Size([2, 1])
t10 = torch.tensor([7])  # torch.Size([1])
print(t7 + t8)   # >>> tensor([[4, 3], [3, 4]])
print(t7 + t9)   # >>> tensor([[6, 7], [2, 5]])
print(t8 + t9)   # >>> tensor([[8, 6], [5, 3]])
print(t7 + t10)  # >>> tensor([[ 8, 9], [ 7, 10]])

print("#" * 50, 5)

t11 = torch.ones(4, 3, 2)
t12 = t11 * torch.rand(3, 2)  # 3rd & 2nd dims identical to t11, dim 0 absent
print(t12.shape)

t13 = torch.ones(4, 3, 2)
t14 = t13 * torch.rand(3, 1)  # 3rd dim = 1, 2nd dim is identical to t13
print(t14.shape)

t15 = torch.ones(4, 3, 2)
t16 = t15 * torch.rand(1, 2)  # 3rd dim is identical to t15, 2nd dim is 1
print(t16.shape)

t17 = torch.ones(5, 3, 4, 1)
t18 = torch.rand(3, 1, 1)  # 2nd dim is identical to t17, 3rd and 4th dims are 1
print((t17 + t18).size())

print("#" * 50, 6)

t19 = torch.empty(5, 1, 4, 1)
t20 = torch.empty(3, 1, 1)
print((t19 + t20).size())  # torch.Size([5, 3, 4, 1])

t21 = torch.empty(1)
t22 = torch.empty(3, 1, 7)
print((t21 + t22).size())  # torch.Size([3, 1, 7])

t23 = torch.ones(3, 3, 3)
t24 = torch.ones(3, 1, 3)
print((t23 + t24).size())  # torch.Size([3, 3, 3])

# t25 = torch.empty(5, 2, 4, 1)
# t26 = torch.empty(3, 1, 1)
# print((t25 + t26).size())
# RuntimeError: The size of tensor a (2) must match
# the size of tensor b (3) at non-singleton dimension 1

print("#" * 50, 7)

# 크기 4의 텐서에 5를 곱한다.
t27 = torch.ones(4) * 5
print(t27)  # >>> tensor([ 5, 5, 5, 5])

# 각 원소를 제곱한다.
t28 = torch.pow(t27, 2)
print(t28)  # >>> tensor([ 25, 25, 25, 25])

exp = torch.arange(1., 5.)  # tensor([ 1.,  2.,  3.,  4.])
a = torch.arange(1., 5.)  # tensor([ 1.,  2.,  3.,  4.])
t29 = torch.pow(a, exp) # 각 원소를 대응되는 지수로 거듭제곱한다.
print(t29)  # >>> tensor([   1.,    4.,   27.,  256.])


tensor([2., 4., 6.])
################################################## 1
tensor([[-4, -4],
        [-2, -1],
        [ 6,  5]])
################################################## 2
tensor([[3., 4.],
        [5., 6.]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])
################################################## 3
torch.Size([3, 28, 28])
################################################## 4
tensor([[4, 3],
        [3, 4]])
tensor([[6, 7],
        [2, 5]])
tensor([[8, 6],
        [5, 3]])
tensor([[ 8,  9],
        [ 7, 10]])
################################################## 5
torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([5, 3, 4, 1])
################################################## 6
torch.Size([5, 3, 4, 1])
torch.Size([3, 1, 7])
torch.Size([3, 3, 3])
################################################## 7
tensor([5., 5., 5., 5.])
tensor([25., 25., 25., 25.])
tensor([  1

j_tensosr_indexing_slicing

In [22]:
import torch

# 3x5 크기의 텐서를 생성한다.
x = torch.tensor(
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9],
   [10, 11, 12, 13, 14]]
)

print(x[1])  # >>> tensor([5, 6, 7, 8, 9]) / 첫 번째 행
print(x[:, 1])  # >>> tensor([1, 6, 11]) / 두 번째 열의 모든 값
print(x[1, 2])  # >>> tensor(7) / 두 번째 행, 세 번째 열의 값
print(x[:, -1])  # >>> tensor([4, 9, 14) / 마지막 열의 모든 값

print("#" * 50, 1)

print(x[1:])  # >>> tensor([[ 5,  6,  7,  8,  9], [10, 11, 12, 13, 14]]) / 첫 번째 행 제외하고 나머지
print(x[1:, 3:])  # >>> tensor([[ 8,  9], [13, 14]]) / 첫 번째 행 제외하고 3번째 열부터 마지막 열까지

print("#" * 50, 2)

y = torch.zeros((6, 6)) # 6x6 텐서를 0으로 초기화한다.
y[1:4, 2] = 1 # 2번째부터 4번째 행, 3번째 열에 1을 할당한다.
print(y)

print(y[1:4, 1:4]) # 2~4번째 행과 2~4번째 열

print("#" * 50, 3)

# 3x4 크기의 텐서를 생성한다.
z = torch.tensor(
  [[1, 2, 3, 4],
   [2, 3, 4, 5],
   [5, 6, 7, 8]]
)
print(z[:2]) # 1번째와 2번째 행
print(z[1:, 1:3]) # 1번째 행 제외하고 2번째 열과 3번째 열
print(z[:, 1:]) # 모든 행에 대해서 2번째 열부터 마지막 열

z[1:, 1:3] = 0 # 두번째 행부터 마지막 행까지의 1번쨰와 2번째 열을 0으로 설정한다.
print(z)

tensor([5, 6, 7, 8, 9])
tensor([ 1,  6, 11])
tensor(7)
tensor([ 4,  9, 14])
################################################## 1
tensor([[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])
tensor([[ 8,  9],
        [13, 14]])
################################################## 2
tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
tensor([[0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.]])
################################################## 3
tensor([[1, 2, 3, 4],
        [2, 3, 4, 5]])
tensor([[3, 4],
        [6, 7]])
tensor([[2, 3, 4],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[1, 2, 3, 4],
        [2, 0, 0, 5],
        [5, 0, 0, 8]])


k_tensor_reshaping

In [23]:
import torch

# 2x3 크기의 텐서 생성
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])

# t1의 크기를 (3,2)로 변경
t2 = t1.view(3, 2)  # Shape becomes (3, 2)
# t1의 크기를 (1,6)으로 변경
t3 = t1.reshape(1, 6)  # Shape becomes (1, 6)
print(t2)
print(t3)

# 0부터 7까지의 값을 가지는 텐서를 (2,4) 크기로 변경
t4 = torch.arange(8).view(2, 4)  # Shape becomes (2, 4)
# 0부터 5까지의 값을 가지는 텐서를 (2,3) 크기로 변경
t5 = torch.arange(6).view(2, 3)  # Shape becomes (2, 3)
print(t4)
print(t5)

print("#" * 50, 1)

# Original tensor with shape (1, 3, 1)
t6 = torch.tensor([[[1], [2], [3]]])

# Remove all dimensions of size 1
t7 = t6.squeeze()  # Shape becomes (3,)

# Remove dimension at position 0
t8 = t6.squeeze(0)  # Shape becomes (3, 1)
print(t7)
print(t8)

print("#" * 50, 2)

# Original tensor with shape (3,)
t9 = torch.tensor([1, 2, 3])

# Add a new dimension at position 1
t10 = t9.unsqueeze(1)  # Shape becomes (3, 1)
print(t10)

t11 = torch.tensor(
  [[1, 2, 3],
   [4, 5, 6]]
)
# 1번째 차원에 새로운 차원 추가
t12 = t11.unsqueeze(1)  # Shape becomes (2, 1, 3)
print(t12, t12.shape)

print("#" * 50, 3)

# Original tensor with shape (2, 3)
t13 = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Flatten the tensor / 텐서를 일차원으로 펼치기
t14 = t13.flatten()  # Shape becomes (6,)

print(t14)

# Original tensor with shape (2, 2, 2)
t15 = torch.tensor([[[1, 2],
                     [3, 4]],
                    [[5, 6],
                     [7, 8]]])
t16 = torch.flatten(t15)

# 1번째 차원 이후부터 펼치기
t17 = torch.flatten(t15, start_dim=1)

print(t16)
print(t17)

print("#" * 50, 4)

t18 = torch.randn(2, 3, 5)
print(t18.shape)  # >>> torch.Size([2, 3, 5])
# 텐서 차원 재배열
print(torch.permute(t18, (2, 0, 1)).size())  # >>> torch.Size([5, 2, 3])

# Original tensor with shape (2, 3)
t19 = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Permute the dimensions / 차원을 재배열 (dims=(0, 1)은 원래 차원을 유지)
t20 = torch.permute(t19, dims=(0, 1))  # Shape becomes (2, 3) still
# 차원을 재배열 (0번째와 1번째 차원을 교환)
t21 = torch.permute(t19, dims=(1, 0))  # Shape becomes (3, 2)
print(t20)
print(t21)

# Transpose the tensor
t22 = torch.transpose(t19, 0, 1)  # Shape becomes (3, 2)

print(t22)

# torch.t() = 행과 열을 교환하는 전치 함수
t23 = torch.t(t19)  # Shape becomes (3, 2)

print(t23)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[0, 1, 2],
        [3, 4, 5]])
################################################## 1
tensor([1, 2, 3])
tensor([[1],
        [2],
        [3]])
################################################## 2
tensor([[1],
        [2],
        [3]])
tensor([[[1, 2, 3]],

        [[4, 5, 6]]]) torch.Size([2, 1, 3])
################################################## 3
tensor([1, 2, 3, 4, 5, 6])
tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
################################################## 4
torch.Size([2, 3, 5])
torch.Size([5, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


l_tensosr_concat

In [24]:
import torch

t1 = torch.zeros([2, 1, 3])
t2 = torch.zeros([2, 3, 3])
t3 = torch.zeros([2, 2, 3])

# 1번째 차원을 기준으로 t1, t2, t3를 연결한다.
t4 = torch.cat([t1, t2, t3], dim=1)
print(t4.shape)

print("#" * 50, 1)

t5 = torch.arange(0, 3)  # tensor([0, 1, 2])
t6 = torch.arange(3, 8)  # tensor([3, 4, 5, 6, 7])

# 0번째 차원을 기준으로 t5, t6를 연결한다.
t7 = torch.cat((t5, t6), dim=0)
print(t7.shape)  # >>> torch.Size([8])
print(t7)  # >>> tensor([0, 1, 2, 3, 4, 5, 6, 7])

print("#" * 50, 2)

t8 = torch.arange(0, 6).reshape(2, 3)  # torch.Size([2, 3])
t9 = torch.arange(6, 12).reshape(2, 3)  # torch.Size([2, 3])

# 2차원 텐서간 병합
t10 = torch.cat((t8, t9), dim=0)
print(t10.size())  # >>> torch.Size([4, 3])
print(t10)
# >>> tensor([[ 0,  1,  2],
#             [ 3,  4,  5],
#             [ 6,  7,  8],
#             [ 9, 10, 11]])

t11 = torch.cat((t8, t9), dim=1)
print(t11.size())  # >>>torch.Size([2, 6])
print(t11)
# >>> tensor([[ 0,  1,  2,  6,  7,  8],
#             [ 3,  4,  5,  9, 10, 11]])

print("#" * 50, 3)

t12 = torch.arange(0, 6).reshape(2, 3)  # torch.Size([2, 3])
t13 = torch.arange(6, 12).reshape(2, 3)  # torch.Size([2, 3])
t14 = torch.arange(12, 18).reshape(2, 3)  # torch.Size([2, 3])

t15 = torch.cat((t12, t13, t14), dim=0)
print(t15.size())  # >>> torch.Size([6, 3])
print(t15)
# >>> tensor([[ 0,  1,  2],
#             [ 3,  4,  5],
#             [ 6,  7,  8],
#             [ 9, 10, 11],
#             [12, 13, 14],
#             [15, 16, 17]])

t16 = torch.cat((t12, t13, t14), dim=1)
print(t16.size())  # >>> torch.Size([2, 9])
print(t16)
# >>> tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
#             [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])

print("#" * 50, 4)

t17 = torch.arange(0, 6).reshape(1, 2, 3)  # torch.Size([1, 2, 3])
t18 = torch.arange(6, 12).reshape(1, 2, 3)  # torch.Size([1, 2, 3])

t19 = torch.cat((t17, t18), dim=0)
print(t19.size())  # >>> torch.Size([2, 2, 3])
print(t19)
# >>> tensor([[[ 0,  1,  2],
#              [ 3,  4,  5]],
#             [[ 6,  7,  8],
#              [ 9, 10, 11]]])

t20 = torch.cat((t17, t18), dim=1)
print(t20.size())  # >>> torch.Size([1, 4, 3])
print(t20)
# >>> tensor([[[ 0,  1,  2],
#              [ 3,  4,  5],
#              [ 6,  7,  8],
#              [ 9, 10, 11]]])

t21 = torch.cat((t17, t18), dim=2)
print(t21.size())  # >>> torch.Size([1, 2, 6])
print(t21)
# >>> tensor([[[ 0,  1,  2,  6,  7,  8],
#              [ 3,  4,  5,  9, 10, 11]]])

torch.Size([2, 6, 3])
################################################## 1
torch.Size([8])
tensor([0, 1, 2, 3, 4, 5, 6, 7])
################################################## 2
torch.Size([4, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
torch.Size([2, 6])
tensor([[ 0,  1,  2,  6,  7,  8],
        [ 3,  4,  5,  9, 10, 11]])
################################################## 3
torch.Size([6, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])
torch.Size([2, 9])
tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
        [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])
################################################## 4
torch.Size([2, 2, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 4, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 2, 6])
t

m_tensor_stacking

In [25]:
import torch

t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = torch.tensor([[7, 8, 9], [10, 11, 12]])

# 0번째 차원에서 두 텐서를 쌓는다.
t3 = torch.stack([t1, t2], dim=0)
t4 = torch.cat([t1.unsqueeze(dim=0), t2.unsqueeze(dim=0)], dim=0) # unsqueeze를 통해 차원을 확장한다.
print(t3.shape, t3.equal(t4))

# 1번째 차원에서 두 텐서를 쌓는다.
t5 = torch.stack([t1, t2], dim=1)
t6 = torch.cat([t1.unsqueeze(dim=1), t2.unsqueeze(dim=1)], dim=1)
print(t5.shape, t5.equal(t6))

# 2번째 차원에서 두 텐서를 쌓는ㄷ나.
t7 = torch.stack([t1, t2], dim=2)
t8 = torch.cat([t1.unsqueeze(dim=2), t2.unsqueeze(dim=2)], dim=2)
print(t7.shape, t7.equal(t8))

print("#" * 50, 1)

t9 = torch.arange(0, 3)  # tensor([0, 1, 2])
t10 = torch.arange(3, 6)  # tensor([3, 4, 5])

print(t9.size(), t10.size())
# >>> torch.Size([3]) torch.Size([3])

t11 = torch.stack((t9, t10), dim=0)
print(t11.size())  # >>> torch.Size([2,3])
print(t11)
# >>> tensor([[0, 1, 2],
#             [3, 4, 5]])

t12 = torch.cat((t9.unsqueeze(0), t10.unsqueeze(0)), dim=0)
print(t11.equal(t12))
# >>> True

t13 = torch.stack((t9, t10), dim=1)
print(t13.size())  # >>> torch.Size([3,2])
print(t13)
# >>> tensor([[0, 3],
#             [1, 4],
#             [2, 5]])
t14 = torch.cat((t9.unsqueeze(1), t10.unsqueeze(1)), dim=1)
print(t13.equal(t14))
# >>> True


torch.Size([2, 2, 3]) True
torch.Size([2, 2, 3]) True
torch.Size([2, 3, 2]) True
################################################## 1
torch.Size([3]) torch.Size([3])
torch.Size([2, 3])
tensor([[0, 1, 2],
        [3, 4, 5]])
True
torch.Size([3, 2])
tensor([[0, 3],
        [1, 4],
        [2, 5]])
True


* torch.stack()은 새 차원을 추가하면서 텐서를 쌓는다.
* torch.cat()은 차원을 추가하지 않고 기존 차원에서 텐서를 이어붙인다.
* cat을 사용할 때는 unsqueeze()를 사용하여 차원을 확장한다.

n_tensor_vstack_hstack

In [26]:
import torch

# 1차원 텐서 2개 생성
t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([4, 5, 6])
# 두 텐서를 수직으로 결합해 2차원 텐서 생성
t3 = torch.vstack((t1, t2))
print(t3)
# >>> tensor([[1, 2, 3],
#             [4, 5, 6]])

# 2차원 텐서 2개 생성
t4 = torch.tensor([[1], [2], [3]])
t5 = torch.tensor([[4], [5], [6]])

# 수직으로 결합하여 6x1 텐서 생성
t6 = torch.vstack((t4, t5))
# >>> tensor([[1],
#             [2],
#             [3],
#             [4],
#             [5],
#             [6]])

t7 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t7.shape)
# >>> (2, 2, 3)

t8 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t8.shape)
# >>> (2, 2, 3)

# (2, 2, 3) 크기의 3차원 텐서를 수직으로 결합 -> 첫 번째 차원 확장
t9 = torch.vstack([t7, t8])
print(t9.shape)
# >>> (4, 2, 3)

print(t9)
# >>> tensor([[[ 1,  2,  3],
#              [ 4,  5,  6]],
#             [[ 7,  8,  9],
#              [10, 11, 12]],
#             [[13, 14, 15],
#              [16, 17, 18]],
#             [[19, 20, 21],
#              [22, 23, 24]]])

print("#" * 50, 1)

t10 = torch.tensor([1, 2, 3])
t11 = torch.tensor([4, 5, 6])
# 두 텐서를 수평으로 결합해 1차원 텐서 생성
t12 = torch.hstack((t10, t11))
print(t12)
# >>> tensor([1, 2, 3, 4, 5, 6])

t13 = torch.tensor([[1], [2], [3]])
t14 = torch.tensor([[4], [5], [6]])
# 두 텐서를 수평으로 결합해 각 행에 두 열이 추가된 텐서 생성
t15 = torch.hstack((t13, t14))
print(t15)
# >>> tensor([[1, 4],
#             [2, 5],
#             [3, 6]])

t16 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t16.shape)
# >>> (2, 2, 3)

t17 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t17.shape)
# >>> (2, 2, 3)

# 두 텐서를 수평으로 결합 -> 두 번째 차원 확장
t18 = torch.hstack([t16, t17])
print(t18.shape)
# >>> (2, 4, 3)

print(t18)
# >>> tensor([[[ 1,  2,  3],
#              [ 4,  5,  6],
#              [13, 14, 15],
#              [16, 17, 18]],
#             [[ 7,  8,  9],
#              [10, 11, 12],
#              [19, 20, 21],
#              [22, 23, 24]]])


tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([4, 2, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]])
################################################## 1
tensor([1, 2, 3, 4, 5, 6])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([2, 4, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [13, 14, 15],
         [16, 17, 18]],

        [[ 7,  8,  9],
         [10, 11, 12],
         [19, 20, 21],
         [22, 23, 24]]])


* torch.vstack(): 텐서를 수직으로 쌓는다. 1차원, 2차원 텐서를 수직으로 결합하여 새로운 차원을 형성한다.
* torch.hstack(): 텐서를 수평으로 쌓는다. 같은 차원에서 텐서의 열을 결합한다.

__느낀점__
이번 과제를 통해 PyTorch의 텐서 초기화 방법과 다양한 연산에 대해 깊이 있게 학습할 수 있었다. torch.Tensor와 torch.tensor의 차이, 그리고 torch.as_tensor의 활용법을 이해할 수 있었다. 리스트나 넘파이 배열을 텐서로 변환할 때 메모리를 공유할지, 값을 복사할지에 따라 사용하는 함수가 다르다는 것을 알 수 있었다. 브로드캐스팅 기능과 행렬 연산을 pytorch에서 사용하는 방법을 알 수 있었다. 또한, 파이썬 문법을 다시 한 번 공부해야 겠다는 생각이 들었다.